#!/usr/bin/env bash

set -e

local_changes=$(git status --short)

if [ "$local_changes" = "" ]; then
	release-it --ci
else
	echo "Cannot release because of local changes:"
	echo "$local_changes"
	exit 1
fi
