#!/usr/bin/env bash

set -e

local_changes=$(git status --short)

if [ "$local_changes" = "" ]; then
	release-it --ci
else
	echo "Cannot release because of local changes for these files:"
	echo "$local_changes"
	echo "Differences:"
	git diff HEAD
	exit 1
fi
