---
name: Release and Deploy
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  release-and-deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Run flake checks
        run: nix flake check --show-trace
      - name: Set up git user email
        run: >
          nix develop -c
          git config --global user.email 'maciej.laciak@gmail.com'
      - name: Set up git user name
        run: >
          nix develop -c
          git config --global user.name 'mstream'
      - name: Test the library
        run: >
          nix develop -c
          ./test.sh
      - name: Build web application
        run: >
          nix develop -c
          ./docs.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result/html
